import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <div className="navbar-menu">
        <div className="navbar-start">
          <nav className="navbar">
            <Link href="/" className="navbar-item">
              Users
            </Link>
            <Link href="/users/add" className="navbar-item">
              Add User
            </Link>
          </nav>
        </div>
      </div>
        {children}</body>
    </html>
  );
}
